- name: execute all as virt_user
  become: true
  become_user: "{{ virt_user }}"
  tags:
    - images
    - undercloud
    - lab
  block:
    - name: Activate swap only if needed
      set_fact:
        enable_swap: "{{ undercloud_swap is defined and undercloud_swap |bool }}"

    - name: undercloud image settings
      shell: |
        export LIBGUESTFS_BACKEND=direct
        virt-sysprep -a "{{basedir}}/workload/{{vm_prefix}}-{{ item.name }}.qcow2" \
          --firstboot-command "growpart /dev/sda {{ root_device }}" \
          --firstboot-command "xfs_growfs {{ growfs_part }}" \
        {% if enable_swap | bool %}
          --firstboot-command "mkswap /dev/sdb" \
          --firstboot-command "swapon /dev/sdb" \
        {% endif %}
          --hostname {{ undercloud_hostname | lower }} \
          --uninstall cloud-init \
          --selinux-relabel \
          --root-password "password:{{undercloud_password}}" \
          --ssh-inject root:file:{{ basedir }}/.ssh/authorized_keys \
          --delete /etc/machine-id &> "{{basedir}}/workload/{{vm_prefix}}-{{ item.name }}.qcow2.done"
      args:
        creates: "{{basedir}}/workload/{{vm_prefix}}-{{ item.name }}.qcow2.done"
      when:
        - item.name is match('^undercloud')
      loop: "{{ vms }}"
      loop_control:
        label: "{{ item.name }}"

