---
- name: generate baremetal.json file
  when:
    - hostvars['builder'] is defined
    - hostvars['builder']['oc_mac_addresses'] is defined
  tags:
    - lab
    - overcloud
    - baremetal
  template:
    dest: /home/stack/baremetal.json
    mode: '0644'
    src: baremetal.json.j2

- name: Ensure baremetal.json is present
  register: baremetal_exists
  stat:
    path: /home/stack/baremetal.json

- name: Fail if baremetal.json doesn't exist
  when:
    - not baremetal_exists.stat.exists
  fail:
    msg: |
      Playbook didn't generate baremetal.json.
      This might be due to the lack of parameter.
      Please re-run, ensuring -t domains is passed!

- name: check overcloud node import status
  tags:
    - lab
    - baremetal
    - overcloud
  when:
    - deploy_undercloud|bool
    - vms|length > 1
  shell: |
    source ~/stackrc
    openstack baremetal node list -f value -c UUID
  register: known_bm

- name: debug value
  tags:
    - lab
    - baremetal
    - overcloud
  when:
    - deploy_undercloud|bool
    - vms|length > 1
  debug:
    msg: "Got {{ known_bm.stdout_lines|length }} instance(s) (should have {{ vms|length -1 }})"

#- name: Update references if needed
#  tags:
#    - lab
#    - overcloud
#    - overcloud-images
#  when:
#    - deploy_undercloud|bool
#    - new_oc_image|bool
#    - known_bm.stdout_lines|default([])|length > 1
#  import_role:
#    name: tripleo.operator.tripleo_overcloud_node_configure
#  vars:
#    tripleo_overcloud_node_configure_all_manageable: true

- name: Import and provide for metalsmith
  tags:
    - lab
    - baremetal
    - overcloud
  when:
    - vms|length > 1
    - known_bm.stdout_lines|default([])|length != (vms|length - 1)
  block:
    - name: Import nodes in Ironic and provide them
      import_role:
        name: tripleo.operator.tripleo_overcloud_node_import
      vars:
        tripleo_overcloud_node_import_generate_scripts_only: "{{ not deploy_undercloud | bool }}"
        tripleo_overcloud_node_import_environment_file: ~/baremetal.json
        tripleo_overcloud_node_import_provide: true

- name: Metalsmith-based node deploy
  tags:
    - lab
    - baremetal
    - overcloud
  when:
    - metalsmith | default(true)
    - vms|length > 1
  import_tasks: metalsmith.yaml
