- name: Set OC images base uri
  set_fact:
    oc_img_base_uri: >-
      {%- if oc_img_base_uri is defined -%}
      {{ oc_img_base_uri }}
      {%- else -%}
      https://images.rdoproject.org/centos{{ os_version }}/{{tripleo_repos_branch}}/rdo_trunk/{{ oc_img_line | default('current-tripleo') }}/
      {%- endif -%}
- name: "Link for CentOS{{os_version}} OC images"
  debug:
    var: oc_img_base_uri
- name: "fetch images for centos{{ os_version }}"
  environment:
    http_proxy: "{{ proxy_host | default('') }}"
    https_proxy: "{{ proxy_host | default('') }}"
  get_url:
    dest: "/home/stack/overcloud_imgs/{{item.file}}"
    mode: 0644
    url: "{{ oc_img_base_uri }}/{{item.file}}"
  retries: 10
  delay: 5
  loop: "{{ overcloud_images }}"
  loop_control:
    label: "{{item.file}}"

- name: uncompress images
  register: uncompress_centos_img
  unarchive:
    creates: "/home/stack/overcloud_imgs/{{item.content}}"
    dest: "/home/stack/overcloud_imgs/"
    remote_src: true
    src: "/home/stack/overcloud_imgs/{{item.file}}"
  loop: "{{ overcloud_images }}"
  loop_control:
    label: "{{item.file}}"
