---
- import_tasks: packages.yaml
- import_tasks: config.yaml
- import_tasks: scripts.yaml
- import_tasks: manage-oc-images.yaml
- import_tasks: upload.yaml
- import_tasks: networks.yaml
  when: network_data_v2 | bool
  tags:
    - lab
    - overcloud
- import_tasks: baremetal.yaml
  tags:
    - lab
    - overcloud

- import_role:
    name: tripleo.operator.tripleo_container_image_prepare
  vars:
    tripleo_container_image_prepare_environment_files: /home/stack/containers-prepare-parameter.yaml
    tripleo_container_image_prepare_output_env_file: /home/stack/generated-container-prepare-overcloud.yaml
    tripleo_container_image_prepare_log_file: /home/stack/generated-container-prepare-overcloud.log
    tripleo_container_image_prepare_roles_file: /home/stack/oc0-role-data.yaml

- name: Deploy all overclouds
  tags:
    - lab
    - overcloud
  loop: "{{ overclouds_range }}"
  loop_control:
    label: "Deploying overcloud {{ item }}"
  include_tasks: deploy.yaml
