---
- name: install package
  become: true
  become_user: root
  package:
    name: "{{ director_image_pkgs }}"
    state: installed

- name: uncompress images
  register: uncompress_rhel_img
  unarchive:
    creates: "/home/stack/overcloud_imgs/{{item.content}}"
    dest: "/home/stack/overcloud_imgs/"
    remote_src: true
    src: "/usr/share/rhosp-director-images/{{item.file}}"
  loop: "{{ overcloud_images }}"
  loop_control:
    label: "{{item.file}}"
