- name: install custom RPM from remote link
  become: true
  become_user: root
  package:
    name: "{{ custom_rpms }}"
    state: installed
    disable_gpg_check: true
  when: custom_rpms | length > 0

