---
- name: run on nat-vm node
  tags:
    - nat-vm
    - lab
  delegate_to: nat-vm
  delegate_facts: false
  block:
    - name: Ensure we do not rely on GSS for auth
      replace:
        path: /etc/ssh/sshd_config
        regexp: '^GSSAPIAuthentication yes$'
        replace: 'GSSAPIAuthentication no'
      register: sshd_config

    - name: Restart sshd if needed
      service:
        name: sshd
        state: restarted
      when: sshd_config is changed

    - name: Inject proxy for dnf and yum
      when:
        - proxy_host is defined
      include_role:
        name: undercloud_prepare
        tasks_from: proxy.yaml

    - name: set up custom repositories
      yum_repository:
        name: "{{ item.name }}"
        description: "{{ item.name }}"
        file: "{{ item.file | default(item.name) }}"
        baseurl: "{{ item.uri }}"
        gpgcheck: "{{ item.gpg |default(omit) }}"
        priority: "{{ item.priority |default(omit) }}"
        gpgkey: "{{ item.gpgkey |default(omit) }}"
      loop: "{{ custom_repositories }}"

    - name: Update all packages
      tags:
        - updates
      dnf:
        name: "*"
        state: latest
        update_cache: true

    - name: Authorize custom keys on the undercloud
      tags:
        - lab
        - undercloud-bootstrap
      authorized_key:
        user: root
        key: "{{ item }}"
      loop: "{{ stack_ssh_keys | default([]) }}"

    - name: Ensure correct /etc/hosts entry
      lineinfile:
        insertbefore: BOF
        backup: false
        line: "{{ nat_vm_addr.stdout|replace('/24','') }} {{ vm_prefix }}-nat-vm.{{ domain }}"
        path: /etc/hosts

    - name: Remove dracute useless interface
      file:
        path: /etc/sysconfig/network-scripts/ifcfg-ens3
        state: absent

    - name: Add the 802.1q module
      modprobe:
        name: 8021q
        state: present

    - name: Configure proxy
      when: proxy_host is defined
      import_role:
        name: undercloud_prepare
        tasks_from: proxy.yaml

    - name: Install some tools
      package:
        name:
          - bash-completion
          - tcpdump
          - firewalld
          - tmux

    - name: Start and enable firewalld
      service:
        name: firewalld
        enabled: true
        state: started

    - name: Create vlan interface
      command: |
        nmcli con add type vlan con-name vlan-{{ item + 100 }} vlan.parent eth1 vlan.id {{ item + 100 }} ip4 "192.168.{{ 100 + item }}.1/24"
      args:
        creates: "/etc/sysconfig/network-scripts/ifcfg-vlan{{ item + 100 }}"
      loop: "{{ overclouds_range }}"
      loop_control:
        label: "vlan-{{item+1}}9"

    - name: Start vlan interfaces
      command: nmcli con up vlan-{{ item + 100 }}
      loop: "{{ overclouds_range }}"
      loop_control:
        label: "vlan-{{item+1}}9"

    - name: Accept NAT
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present

    - name: Add masquerade on public zone
      firewalld:
        masquerade: "true"
        zone: public
        immediate: true
        permanent: true
        state: enabled
